<?php


namespace app\models;


use yii\db\ActiveRecord;

class BccArrearsInfo extends ActiveRecord
{
    private $taxDataId;
    private $bcc;
    private $bccNameRu;
    private $bccNameKz;
    private $taxArrear;
    private $poenaArrear;
    private $percentArrear;
    private $fineArrear;
    private $totalArrear;

    public function rules()
    {
        return [
            [[
                'taxDataId',
                'bcc',
                'bccNameRu',
                'bccNameKz',
                'taxArrear',
                'poenaArrear',
                'percentArrear',
                'fineArrear',
                'totalArrear'
            ],'safe']
        ];
    }

    public function attributeLabels()
    {
        return [
            'taxDataId' => 'Tax Data ID',
            'bcc' => 'КБК:',
            'bccNameRu' => 'КБК:',
            'bccNameKz' => 'КБК:',
            'taxArrear' => 'Задолженность по налогам:',
            'poenaArrear' => 'Задолженность пени',
            'percentArrear' => 'Процент задолженности:',
            'fineArrear' => 'Задолженность:',
            'totalArrear' => 'Общая задолженность:'
        ];
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub

        return true;
    }


}
