<?php


namespace app\models;


use yii\db\ActiveRecord;

class TaxPayerInfo extends ActiveRecord
{
    private $taxDataId;
    private $nameRu;
    private $nameKk;
    private $iinBin;
    private $totalArrear;
    public $bccArrearsInfo;

    private $bccArrearsInfoCollection = [];

    public function rules()
    {
        return [
            [[
                'taxDataId',
                'nameRu',
                'nameKk',
                'iinBin',
                'totalArrear',
                'bccArrearsInfo'
            ],'safe',]
        ];
    }

    public function attributeLabels()
    {
        return [
            'taxDataId' => 'Tax Data ID',
            'nameRu' => 'Наименование налогоплательщика:',
            'nameKk' => 'Наименование налогоплательщика:',
            'iinBin' => 'ИИН налогоплательщика:',
            'totalArrear' => 'Всего задолженности (тенге):',
            'bccArrearsInfo' => 'bccArrearsInfo'
        ];
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub

        foreach ($this->bccArrearsInfo as $key => $value) {
            if ($value != null)
            {
                $bccArrearsInfo = new BccArrearsInfo();
                $bccArrearsInfo->taxDataId = $this->getAttribute('taxDataId');
                $bccArrearsInfo->load($value, '');
                $bccArrearsInfo->save();
            }
        }

        return true;
    }
}
